org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.configuration-cache=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=true
android.overridePathCheck=true
